export type Language = 'it' | 'pl' | 'sk' | 'cs' | 'ro';

type Translations = {
  [key: string]: string;
};

export const languages: Record<Language, { name: string; translations: Translations }> = {
  it: {
    name: 'Italiano',
    translations: {
      home: 'Home',
      shop: 'Shop',
      about: 'Chi Siamo',
      contacts: 'Contatti',
      faq: 'FAQ',
      discoverNewProducts: 'Scopri i nuovi prodotti',
      fastShipping: 'Spedizione Veloce',
      fastShippingDesc: 'Consegna rapida e affidabile in tutta Italia.',
      securePayments: 'Pagamenti Sicuri',
      securePaymentsDesc: 'Transazioni protette con i migliori standard di sicurezza.',
      customerSupport: 'Supporto Clienti',
      customerSupportDesc: 'Il nostro team è sempre a tua disposizione per aiutarti.',
      stayUpdated: 'Rimani Aggiornato',
      newsletterDescription: 'Iscriviti alla nostra newsletter per ricevere sconti esclusivi e anteprime sui nuovi arrivi.',
      yourEmail: 'La tua email',
      subscribe: 'Iscriviti',
      information: 'INFORMAZIONI',
      aboutUs: 'Chi Siamo',
      newArrivals: 'Nuovi Arrivi',
      bestsellers: 'Bestseller',
      allCovers: 'Tutte le Cover',
      policy: 'POLICY',
      privacyPolicy: 'Privacy Policy',
      cookiePolicy: 'Cookie Policy',
      termsAndConditions: 'Termini e Condizioni',
      followUs: 'SEGUICI',
      adminPanel: 'Admin Panel',
      allRightsReserved: 'Tutti i diritti riservati',
      buyNow: 'Acquista Ora',
      view: 'Visualizza',
      loading: 'Caricamento in corso...',
      siteConfigNotFound: 'Configurazione del sito non trovata.',
      allProducts: 'Tutti i Prodotti',
      contactInfo: 'Per qualsiasi informazione, scrivici a',
      faqTitle: 'Domande Frequenti (FAQ)',
      login: 'Accesso',
      username: 'Username',
      password: 'Password',
      invalidCredentials: 'Credenziali non valide. Riprova.',
      loggingIn: 'Accesso in corso...',
      addProductToPreview: "Aggiungi almeno un prodotto per vedere l'anteprima.",
      backToShop: 'Torna allo Shop',
      verifiedBuyer: 'Acquirente Verificato',
      remaining: 'Rimasti',
      previousImage: 'Immagine precedente',
      nextImage: 'Immagine successiva',
      chooseQuantity: 'Scegli la quantità',
      perCover: 'per cover',
      addToCart: 'Aggiungi al Carrello',
      description: 'Descrizione',
      delivery: 'Consegna',
      warranty: 'Garanzia',
      manual: 'Manuale',
      customerReviews: 'Recensioni dei Clienti',
      cartIsEmpty: 'Il tuo carrello è vuoto.',
      completeYourOrder: 'Completa il tuo Ordine',
      orderSummary: 'Riepilogo Ordine',
      quantity: 'Quantità',
      total: 'Totale',
      codNoExtraCost: 'Pagamento alla consegna. Nessun costo aggiuntivo.',
      enterShippingDetails: 'Inserisci i tuoi dati di spedizione',
      completeOrderAndPay: 'Completa Ordine e Paga alla Consegna',
      thankYouTitle: 'Grazie per il tuo ordine!',
      thankYouMessage: "Il tuo ordine è stato ricevuto correttamente. Verrai ricontattato telefonicamente da un nostro operatore per confermare l'ordine e per poter procedere con la spedizione.",
      backToHome: 'Torna alla Home',
      close: 'Chiudi',
      shippingDetails: 'Dati di spedizione',
      fullName: 'Nome e Cognome',
      fullNamePlaceholder: 'Mario Rossi',
      fullAddress: 'Indirizzo Completo (Via, Numero, CAP, Città)',
      fullAddressPlaceholder: 'Via Roma 1, 00100 Roma (RM)',
      phoneNumber: 'Numero di Telefono (per il corriere)',
      phoneNumberPlaceholder: '3331234567',
      emailOptional: 'Email (facoltativa)',
      emailPlaceholder: 'mario.rossi@email.com',
    },
  },
  pl: {
    name: 'Polski',
    translations: {
        home: 'Strona główna',
        shop: 'Sklep',
        about: 'O nas',
        contacts: 'Kontakt',
        faq: 'FAQ',
        discoverNewProducts: 'Odkryj nowe produkty',
        fastShipping: 'Szybka wysyłka',
        fastShippingDesc: 'Szybka i niezawodna dostawa na terenie całych Włoch.',
        securePayments: 'Bezpieczne płatności',
        securePaymentsDesc: 'Transakcje chronione najlepszymi standardami bezpieczeństwa.',
        customerSupport: 'Obsługa klienta',
        customerSupportDesc: 'Nasz zespół jest zawsze do Twojej dyspozycji, aby Ci pomóc.',
        stayUpdated: 'Bądź na bieżąco',
        newsletterDescription: 'Zapisz się do naszego newslettera, aby otrzymywać ekskluzywne zniżki i zapowiedzi nowości.',
        yourEmail: 'Twój e-mail',
        subscribe: 'Zapisz się',
        information: 'INFORMACJE',
        aboutUs: 'O nas',
        newArrivals: 'Nowości',
        bestsellers: 'Bestsellery',
        allCovers: 'Wszystkie etui',
        policy: 'POLITYKA',
        privacyPolicy: 'Polityka Prywatności',
        cookiePolicy: 'Polityka Cookies',
        termsAndConditions: 'Regulamin',
        followUs: 'OBSERWUJ NAS',
        adminPanel: 'Panel Administratora',
        allRightsReserved: 'Wszelkie prawa zastrzeżone',
        buyNow: 'Kup teraz',
        view: 'Zobacz',
        loading: 'Ładowanie...',
        siteConfigNotFound: 'Nie znaleziono konfiguracji strony.',
        allProducts: 'Wszystkie produkty',
        contactInfo: 'W razie jakichkolwiek pytań, napisz do nas na',
        faqTitle: 'Często zadawane pytania (FAQ)',
        login: 'Logowanie',
        username: 'Nazwa użytkownika',
        password: 'Hasło',
        invalidCredentials: 'Nieprawidłowe dane logowania. Spróbuj ponownie.',
        loggingIn: 'Logowanie...',
        addProductToPreview: 'Dodaj przynajmniej jeden produkt, aby zobaczyć podgląd.',
        backToShop: 'Wróć do sklepu',
        verifiedBuyer: 'Zweryfikowany kupujący',
        remaining: 'Pozostało',
        previousImage: 'Poprzednie zdjęcie',
        nextImage: 'Następne zdjęcie',
        chooseQuantity: 'Wybierz ilość',
        perCover: 'za etui',
        addToCart: 'Dodaj do koszyka',
        description: 'Opis',
        delivery: 'Dostawa',
        warranty: 'Gwarancja',
        manual: 'Instrukcja',
        customerReviews: 'Opinie klientów',
        cartIsEmpty: 'Twój koszyk jest pusty.',
        completeYourOrder: 'Dokończ swoje zamówienie',
        orderSummary: 'Podsumowanie zamówienia',
        quantity: 'Ilość',
        total: 'Suma',
        codNoExtraCost: 'Płatność przy odbiorze. Bez dodatkowych kosztów.',
        enterShippingDetails: 'Wprowadź swoje dane do wysyłki',
        completeOrderAndPay: 'Dokończ zamówienie i zapłać przy odbiorze',
        thankYouTitle: 'Dziękujemy za Twoje zamówienie!',
        thankYouMessage: 'Twoje zamówienie zostało pomyślnie przyjęte. Nasz operator skontaktuje się z Tobą telefonicznie w celu potwierdzenia zamówienia i przygotowania wysyłki.',
        backToHome: 'Wróć na stronę główną',
        close: 'Zamknij',
        shippingDetails: 'Dane do wysyłki',
        fullName: 'Imię i nazwisko',
        fullNamePlaceholder: 'Jan Kowalski',
        fullAddress: 'Pełny adres (ulica, numer, kod pocztowy, miasto)',
        fullAddressPlaceholder: 'ul. Kwiatowa 1, 00-001 Warszawa',
        phoneNumber: 'Numer telefonu (dla kuriera)',
        phoneNumberPlaceholder: '123456789',
        emailOptional: 'E-mail (opcjonalnie)',
        emailPlaceholder: 'jan.kowalski@email.com',
      },
  },
  sk: {
    name: 'Slovenčina',
    translations: {
        home: 'Domov',
        shop: 'Obchod',
        about: 'O nás',
        contacts: 'Kontakt',
        faq: 'FAQ',
        discoverNewProducts: 'Objavte nové produkty',
        fastShipping: 'Rýchle dodanie',
        fastShippingDesc: 'Rýchle a spoľahlivé doručenie po celom Taliansku.',
        securePayments: 'Bezpečné platby',
        securePaymentsDesc: 'Transakcie chránené najlepšími bezpečnostnými štandardmi.',
        customerSupport: 'Zákaznícka podpora',
        customerSupportDesc: 'Náš tím je vám vždy k dispozícii, aby vám pomohol.',
        stayUpdated: 'Zostaňte v obraze',
        newsletterDescription: 'Prihláste sa na odber nášho newslettera a získajte exkluzívne zľavy a ukážky noviniek.',
        yourEmail: 'Váš e-mail',
        subscribe: 'Prihlásiť sa',
        information: 'INFORMÁCIE',
        aboutUs: 'O nás',
        newArrivals: 'Nové príchody',
        bestsellers: 'Najpredávanejšie',
        allCovers: 'Všetky kryty',
        policy: 'PODMIENKY',
        privacyPolicy: 'Zásady ochrany osobných údajov',
        cookiePolicy: 'Zásady používania súborov cookie',
        termsAndConditions: 'Obchodné podmienky',
        followUs: 'SLEDUJTE NÁS',
        adminPanel: 'Admin Panel',
        allRightsReserved: 'Všetky práva vyhradené',
        buyNow: 'Kúpiť teraz',
        view: 'Zobraziť',
        loading: 'Načítava sa...',
        siteConfigNotFound: 'Konfigurácia stránky sa nenašla.',
        allProducts: 'Všetky produkty',
        contactInfo: 'Pre akékoľvek informácie nám napíšte na',
        faqTitle: 'Často kladené otázky (FAQ)',
        login: 'Prihlásenie',
        username: 'Používateľské meno',
        password: 'Heslo',
        invalidCredentials: 'Neplatné prihlasovacie údaje. Skúste to znova.',
        loggingIn: 'Prihlasovanie...',
        addProductToPreview: 'Pridajte aspoň jeden produkt, aby ste si mohli pozrieť ukážku.',
        backToShop: 'Späť do obchodu',
        verifiedBuyer: 'Overený kupujúci',
        remaining: 'Zostáva',
        previousImage: 'Predchádzajúci obrázok',
        nextImage: 'Nasledujúci obrázok',
        chooseQuantity: 'Vyberte si množstvo',
        perCover: 'za kryt',
        addToCart: 'Pridať do košíka',
        description: 'Popis',
        delivery: 'Doručenie',
        warranty: 'Záruka',
        manual: 'Manuál',
        customerReviews: 'Recenzie zákazníkov',
        cartIsEmpty: 'Váš košík je prázdny.',
        completeYourOrder: 'Dokončite svoju objednávku',
        orderSummary: 'Zhrnutie objednávky',
        quantity: 'Množstvo',
        total: 'Celkom',
        codNoExtraCost: 'Platba na dobierku. Žiadne ďalšie poplatky.',
        enterShippingDetails: 'Zadajte svoje dodacie údaje',
        completeOrderAndPay: 'Dokončiť objednávku a zaplatiť pri doručení',
        thankYouTitle: 'Ďakujeme za vašu objednávku!',
        thankYouMessage: 'Vaša objednávka bola úspešne prijatá. Náš operátor vás bude telefonicky kontaktovať, aby potvrdil objednávku a dohodol odoslanie.',
        backToHome: 'Späť na domovskú stránku',
        close: 'Zavrieť',
        shippingDetails: 'Dodacie údaje',
        fullName: 'Meno a priezvisko',
        fullNamePlaceholder: 'Ján Vážny',
        fullAddress: 'Úplná adresa (ulica, číslo, PSČ, mesto)',
        fullAddressPlaceholder: 'Hlavná 1, 811 01 Bratislava',
        phoneNumber: 'Telefónne číslo (pre kuriéra)',
        phoneNumberPlaceholder: '0912345678',
        emailOptional: 'E-mail (nepovinné)',
        emailPlaceholder: 'jan.vazny@email.com',
      },
  },
  cs: {
    name: 'Čeština',
    translations: {
        home: 'Domů',
        shop: 'Obchod',
        about: 'O nás',
        contacts: 'Kontakty',
        faq: 'FAQ',
        discoverNewProducts: 'Objevte nové produkty',
        fastShipping: 'Rychlé dodání',
        fastShippingDesc: 'Rychlé a spolehlivé doručení po celé Itálii.',
        securePayments: 'Bezpečné platby',
        securePaymentsDesc: 'Transakce chráněné nejlepšími bezpečnostními standardy.',
        customerSupport: 'Zákaznická podpora',
        customerSupportDesc: 'Náš tým je vám vždy k dispozici, aby vám pomohl.',
        stayUpdated: 'Zůstaňte v obraze',
        newsletterDescription: 'Přihlaste se k odběru našeho newsletteru a získejte exkluzivní slevy a ukázky novinek.',
        yourEmail: 'Váš e-mail',
        subscribe: 'Přihlásit se',
        information: 'INFORMACE',
        aboutUs: 'O nás',
        newArrivals: 'Nové přírůstky',
        bestsellers: 'Nejprodávanější',
        allCovers: 'Všechny kryty',
        policy: 'ZÁSADY',
        privacyPolicy: 'Zásady ochrany osobních údajů',
        cookiePolicy: 'Zásady používání souborů cookie',
        termsAndConditions: 'Obchodní podmínky',
        followUs: 'SLEDUJTE NÁS',
        adminPanel: 'Admin Panel',
        allRightsReserved: 'Všechna práva vyhrazena',
        buyNow: 'Koupit nyní',
        view: 'Zobrazit',
        loading: 'Načítání...',
        siteConfigNotFound: 'Konfigurace webu nebyla nalezena.',
        allProducts: 'Všechny produkty',
        contactInfo: 'Pro jakékoli informace nám napište na',
        faqTitle: 'Často kladené otázky (FAQ)',
        login: 'Přihlášení',
        username: 'Uživatelské jméno',
        password: 'Heslo',
        invalidCredentials: 'Neplatné přihlašovací údaje. Zkuste to znovu.',
        loggingIn: 'Přihlašování...',
        addProductToPreview: 'Přidejte alespoň jeden produkt, abyste si mohli prohlédnout náhled.',
        backToShop: 'Zpět do obchodu',
        verifiedBuyer: 'Ověřený kupující',
        remaining: 'Zbývá',
        previousImage: 'Předchozí obrázek',
        nextImage: 'Další obrázek',
        chooseQuantity: 'Vyberte si množství',
        perCover: 'za kryt',
        addToCart: 'Přidat do košíku',
        description: 'Popis',
        delivery: 'Doručení',
        warranty: 'Záruka',
        manual: 'Manuál',
        customerReviews: 'Recenze zákazníků',
        cartIsEmpty: 'Váš košík je prázdný.',
        completeYourOrder: 'Dokončete svou objednávku',
        orderSummary: 'Shrnutí objednávky',
        quantity: 'Množství',
        total: 'Celkem',
        codNoExtraCost: 'Platba na dobírku. Žádné další poplatky.',
        enterShippingDetails: 'Zadejte své dodací údaje',
        completeOrderAndPay: 'Dokončit objednávku a zaplatit při doručení',
        thankYouTitle: 'Děkujeme za vaši objednávku!',
        thankYouMessage: 'Vaše objednávka byla úspěšně přijata. Náš operátor vás bude telefonicky kontaktovat, aby potvrdil objednávku a domluvil odeslání.',
        backToHome: 'Zpět na domovskou stránku',
        close: 'Zavřít',
        shippingDetails: 'Dodací údaje',
        fullName: 'Jméno a příjmení',
        fullNamePlaceholder: 'Jan Novák',
        fullAddress: 'Úplná adresa (ulice, číslo, PSČ, město)',
        fullAddressPlaceholder: 'Hlavní 1, 110 00 Praha 1',
        phoneNumber: 'Telefonní číslo (pro kurýra)',
        phoneNumberPlaceholder: '123456789',
        emailOptional: 'E-mail (nepovinné)',
        emailPlaceholder: 'jan.novak@email.com',
      },
  },
  ro: {
    name: 'Română',
    translations: {
        home: 'Acasă',
        shop: 'Magazin',
        about: 'Despre noi',
        contacts: 'Contact',
        faq: 'FAQ',
        discoverNewProducts: 'Descoperiți produse noi',
        fastShipping: 'Livrare rapidă',
        fastShippingDesc: 'Livrare rapidă și fiabilă în toată Italia.',
        securePayments: 'Plăți sigure',
        securePaymentsDesc: 'Tranzacții protejate cu cele mai bune standarde de securitate.',
        customerSupport: 'Suport clienți',
        customerSupportDesc: 'Echipa noastră este mereu la dispoziția dumneavoastră pentru a vă ajuta.',
        stayUpdated: 'Rămâneți la curent',
        newsletterDescription: 'Abonează-te la newsletter-ul nostru pentru a primi reduceri exclusive și avanpremiere la noile sosiri.',
        yourEmail: 'E-mailul tău',
        subscribe: 'Abonare',
        information: 'INFORMAȚII',
        aboutUs: 'Despre noi',
        newArrivals: 'Sosiri noi',
        bestsellers: 'Cele mai vândute',
        allCovers: 'Toate husele',
        policy: 'POLITICI',
        privacyPolicy: 'Politica de confidențialitate',
        cookiePolicy: 'Politica de cookie-uri',
        termsAndConditions: 'Termeni și condiții',
        followUs: 'URMĂRIȚI-NE',
        adminPanel: 'Panou de administrare',
        allRightsReserved: 'Toate drepturile rezervate',
        buyNow: 'Cumpără acum',
        view: 'Vezi',
        loading: 'Se încarcă...',
        siteConfigNotFound: 'Configurația site-ului nu a fost găsită.',
        allProducts: 'Toate produsele',
        contactInfo: 'Pentru orice informații, scrieți-ne la',
        faqTitle: 'Întrebări frecvente (FAQ)',
        login: 'Autentificare',
        username: 'Nume de utilizator',
        password: 'Parolă',
        invalidCredentials: 'Date de autentificare invalide. Vă rugăm să reîncercați.',
        loggingIn: 'Se autentifică...',
        addProductToPreview: 'Adăugați cel puțin un produs pentru a vedea previzualizarea.',
        backToShop: 'Înapoi la magazin',
        verifiedBuyer: 'Cumpărător verificat',
        remaining: 'Rămase',
        previousImage: 'Imaginea anterioară',
        nextImage: 'Imaginea următoare',
        chooseQuantity: 'Alegeți cantitatea',
        perCover: 'pe husă',
        addToCart: 'Adaugă în coș',
        description: 'Descriere',
        delivery: 'Livrare',
        warranty: 'Garanție',
        manual: 'Manual',
        customerReviews: 'Recenzii clienți',
        cartIsEmpty: 'Coșul tău este gol.',
        completeYourOrder: 'Finalizați comanda',
        orderSummary: 'Rezumatul comenzii',
        quantity: 'Cantitate',
        total: 'Total',
        codNoExtraCost: 'Plată la livrare. Fără costuri suplimentare.',
        enterShippingDetails: 'Introduceți detaliile de livrare',
        completeOrderAndPay: 'Finalizați comanda și plătiți la livrare',
        thankYouTitle: 'Vă mulțumim pentru comanda dumneavoastră!',
        thankYouMessage: 'Comanda dumneavoastră a fost primită cu succes. Un operator vă va contacta telefonic pentru a confirma comanda și a proceda la expediere.',
        backToHome: 'Înapoi la pagina principală',
        close: 'Închide',
        shippingDetails: 'Detalii de livrare',
        fullName: 'Nume și prenume',
        fullNamePlaceholder: 'Ion Popescu',
        fullAddress: 'Adresa completă (stradă, număr, cod poștal, oraș)',
        fullAddressPlaceholder: 'Str. Principală, nr. 1, 010011, București',
        phoneNumber: 'Număr de telefon (pentru curier)',
        phoneNumberPlaceholder: '0712345678',
        emailOptional: 'E-mail (opțional)',
        emailPlaceholder: 'ion.popescu@email.com',
      },
  },
};

export const getTranslations = (lang: Language): ((key: string) => string) => {
  const translations = languages[lang]?.translations || languages.it.translations;
  const fallback = languages.it.translations;
  return (key: string) => translations[key] || fallback[key] || key;
};
